apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: mgo-quickstart
  namespace: demo
spec:
  version: "4.4.6"
  replicaSet:
    name: "rs1"
  replicas: 3
  storageType: Durable
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete

# k exec -it svc/mgo-quickstart -c mongodb -- bash -c 'mongo admin -u $MONGO_INITDB_ROOT_USERNAME -p "$MONGO_INITDB_ROOT_PASSWORD"'
